#
# $Id: Makefile,v 1.1 2000/06/26 17:18:56 rolf Exp $
#
include ../Makefile-common
 
print_id_string.$(CPLANT_ARCH):	print_id_string.$.c
	$(CC) -Wall $< -o $@

clean:
	rm print_id_string.$(CPLANT_ARCH)
