#
# $Id: Makefile,v 1.1.2.1 2002/08/09 21:05:08 jrstear Exp $
#
include ../../Makefile-common

INSTALLDIR = $(initdir)
INSTALLTARGETS = $(shell ls -I CVS -I Makefile)

all:

install: $(INSTALLTARGETS)
	@$($@)

clean:

