#!/bin/bash
# $Id: mount_nfs,v 1.1.2.1 2002/08/09 20:34:00 jrstear Exp $

# parse $2, which is assumed to be of the following format:
#  nfsserver:/path/to/partition,/path/to/mountpoint
serverpartition=`echo $2 | cut -d, -f1`
server=`echo $serverpartition | cut -d: -f1`
mountpoint=`echo $2 | cut -d, -f2`

case "$1" in
    start) 
    	# poll the server for readiness
        while ! ( /usr/sbin/rpcinfo -p $server | grep -q nfs > /dev/null 2>&1 )
        do
	    echo "$0 $1 $2: rpcinfo poll to $server failed..."
            sleep 5
        done

        while ! mount -n $MOUNTOPTIONS $serverpartition $mountpoint
        do
	    echo "$0 $1 $2: mount of $serverpartition failed..."
            sleep 30
        done
	;;

    stop)
        umount $mountpoint
	exit $?
	;;

    restart)
        $0 stop $2
        $0 start $2
	;;

    *)
	echo "Usage:  {start|stop|restart} server:/partition,/mountpoint" 
esac
