#!/bin/bash

# 
# Script to start the ntpd on nodes that need to 
# maintain consistant time with external server
# like nodes running sshd
#
echo "-->> Executing $0 $1"

case "$1" in
    start)
	
        if [ -f /usr/sbin/ntpdate ]
        then
            echo "Setting date via ntpdate...."
            /usr/sbin/ntpdate -s 134.253.138.254
        fi
    
        if [ -f /usr/sbin/xntpd ]
        then
            echo "Starting xntpd...."
            /usr/sbin/xntpd -g -c /etc/ntp.conf
        fi

        ;;

    stop)
            killall xntpd
        ;;
    *)
        echo "Usage: $0  {start|stop}"
esac

echo "-->> Done with $0 $1"
