#!/bin/bash 
# $Id: ram_disk,v 1.1.2.1 2002/08/09 20:34:01 jrstear Exp $

# set the disk size
size=32768  # the default
(test -n "$2") && size=$2  # or, the value passed in

dev="/dev/ram2"

case "$1" in
    start)
        test -d $RAMDISK || mkdir $RAMDISK
        mke2fs -q $dev $size
	# mount returns 1 on success
        mount -n $dev $RAMDISK  ||
	{
            echo "$0 $1 $2: mounting $dev on $RAMDISK failed"
            exit 1
	}
	exit 0  # shells return 0 on success
	;;

    stop)
	# umount returns 1 on success
	umount $RAMDISK ||
	{
            echo "$0 $1 $2: failed to umount $RAMDISK"
            exit 1
	}
	exit 0  # shells return 0 on success
	;;

    restart)
	$0 stop $2
	$0 start $2
	;;
    *)
        echo "Usage: {start|stop|restart} [size]"
esac
