#
# $Id: Makefile,v 1.1 2002/04/29 17:11:36 rklundt Exp $
#

include ../../../../Makefile-common


INSTALLDIR     = $(libdir_sys)/linux
INSTALLTARGETS = for_msg.cat 

all:

clean:

install uninstall:
	@$($@)
