#
# $Id: Makefile,v 1.5 1999/01/28 22:58:46 jotto Exp $
#

include ../../Makefile-common

MAKEFLAGS  = --no-print-directory
SHELL      = /bin/sh
SUBDIR     = $(CPLANT_ARCH)-$(OS)

all:

%:
	$(MAKE) -C $(SUBDIR) $@

