
#
#       @(#)tests.init	1.9 99/02/11 Connectathon testsuite
#
MNTOPTIONS="rw,hard,intr"
MNTPOINT="/a"

# Use this mount command if using:
#	SVR3
#MOUNTCMD='./domount -f NFS,$MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

# Use this mount command if using:
#	SVR4
#	Solaris 2.x
#MOUNTCMD='./domount -F nfs -o $MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

# Use this mount command if using:
#	BSD
#	SunOS 4.X
#	(DEC) OSF/1
#	HPUX
MOUNTCMD='./domount -o $MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

# Use this mount command if using:
#	DG/UX
#MOUNTCMD='./domount -t nfs -o $MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'

UMOUNTCMD='./domount -u $MNTPOINT'

# Use the next two lines if using:
#	SVR3
#	SVR4
#	Solaris 2.x
#	(DEC) OSF1
#	HPUX
#DASHN=
#BLC=\\c

# Use the next two lines if using:
#	BSD
#	SunOS 4.X
DASHN=-n
BLC=

# Use this path for:
#	Solaris 2.x
#PATH=/opt/SUNWspro/bin:/usr/ccs/bin:/sbin:/bin:/usr/bin:/usr/ucb:/etc:.

# Use this path for:
#	Solaris 2.x with GCC
#PATH=/opt/gnu/bin:/usr/ccs/bin:/sbin:/bin:/usr/bin:/usr/ucb:/etc:.

# Use this path for:
#	HPUX
#PATH=/bin:/usr/bin:/etc:/usr/etc:/usr/local/bin:/usr/contrib/bin:.

# Use this path for:
#	BSD
#	SunOS 4.X
PATH=/bin:/usr/bin:/usr/ucb:/etc:/usr/etc:.

# Use this path for:
#	(DEC) OSF/1
#	SVR4
#PATH=/bin:/usr/bin:/usr/ucb:/usr/ccs/bin:/sbin:/usr/sbin:.

# Use this path for:
#	DG/UX
#PATH=/bin:/usr/bin:/usr/ucb:/etc:/usr/etc:.

# Use this path for:
#	IRIX
#PATH=/bin:/usr/bin:/usr/bsd:/etc:/usr/etc:.

SERVER=""
SERVPATH="/server"
TEST="-a"
TESTARG="-t"

# -----------------------------------------------
# Defines for various variables used in scripts and makefiles.
#
# Do not remove the following three lines.  They may be overridden by
# other configuration parameters lower in this file, but these three
# variables must be defined.
CC=cc
CFLAGS=
LIBS=
LOCKTESTS=tlock

# Use with SVR3 systems.
# Add -TR2 to CFLAGS for use on Amdahl UTS systems.
#CFLAGS=-DSVR3
#LIBS=`echo -lrpc -lsocket`

# Use with BSD systems.
CFLAGS=`echo -Duse_directs -DENFS`

# Use with SVR4 systems.
#CFLAGS=-DSVR4
#LIBS=`echo -lsocket -lnsl`

# Use with SunOS 4.X systems
#CC=/usr/5bin/cc
#CFLAGS=`echo -DSUNOS4X -DNEED_STRERROR`

# Use with Solaris 2.x systems.  Need the 5.0 C compiler (or later)
# for 64-bit mode.
#CC=/opt/SUNWspro/bin/cc
# Use this with GCC
#CC=/opt/gnu/bin/gcc
# Use this through Solaris 2.6.  For Solaris 2.7 and later, use
# this for 32-bit mode applications.
#CFLAGS=`echo -DSVR4 -DMMAP -DSOLARIS2X -DSTDARG`
# For Solaris 2.7 and later, use this for 64-bit mode applications.
#CFLAGS=`echo -DSVR4 -DMMAP -DSOLARIS2X -DSTDARG -xO0 -xarch=v9 -dalign -Xt -L/usr/lib/sparcv9`
# Use this with pre-2.2 systems
#LIBS=`echo -lsocket -ltcpip -lstraddr -lnsl`
# Use with 2.2 and later systems
#LIBS=`echo -lsocket -lnsl`
# Use this through Solaris 2.5.1.
#LOCKTESTS=`echo tlock`
# Use with 2.6 and later systems, 32-bit mode.
LOCKTESTS=`echo tlocklfs tlock64`
# Use with 2.7 and later, 64-bit mode.
#LOCKTESTS=`echo tlocklfs`

# Use with (DEC) OSF/1 systems
#CFLAGS=`echo -O -DOSF1 -DMMAP -DSTDARG`
# use the following instead of the above if using gcc
#CFLAGS=`echo -O -DOSF1 -DMMAP -DSTDARG -fwritable-strings`
#MOUNT=/sbin/mount
#UMOUNT=/sbin/umount

# Use with HPUX systems, 10.00 and earlier.
#CFLAGS=-DHPUX
#CC=/bin/cc
#RM=/bin/rm
#MAKE=/bin/make

# Use with HPUX systems, 10.01 and later.
#CFLAGS=`echo -Ae -DHPUX`
#CC=/opt/ansic/bin/cc
#RM=/bin/rm
#MAKE=/usr/bin/make

# Use with DG/UX systems.
#CFLAGS=-DSVR4
#LIBS=`echo -lsocket -lnsl`

# Use with IRIX systems.
#CFLAGS=`echo -w -DSVR4 -DIRIX -DMMAP`

# -----------------------------------------------
