# 
# $Id: Makefile,v 1.7 2001/02/26 17:07:02 rolf Exp $
#

include ../../../Makefile-common

#SUBDIRS   = base pkt tests
SUBDIRS   = p3mod
#MAKEFLAGS = --no-print-directory
SHELL     = /bin/sh

all:

%:
	$(do-subdirs)

