# see ./README for suggested usage of
# following targets

include ../Makefile-common

all:

src_release:
	./src-build

bin_release:
	./make-tbal $(CPLANT_TOP)/.. Cplant.bin.tar.gz

clean: ../../top-release
	rm -rf ../../top-release

