#
# $Id: Makefile,v 1.3 2000/10/27 18:12:15 pumatst Exp $
#
include ../../Makefile-common

HEAD = cplant.h

INSTALLDIR        = $(etcindir)
INSTALLTARGETS    = $(HEAD)

all:

install uninstall cp: $(INSTALLTARGETS)
	@$($@)

clean:
